import { readdirSync, readFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitepress'

const siteDir = dirname(dirname(fileURLToPath(import.meta.url)))

/**
 * The spec pages are generated by `scripts/sync-content.mjs` (which the dev
 * and build scripts run first), so the sidebar is read off disk rather than
 * hand-listed — add a capability to `openspec/specs/` and it shows up here.
 */
function specSidebar() {
  const specsDir = join(siteDir, 'specs')
  if (!existsSync(specsDir)) return []

  return readdirSync(specsDir)
    .filter((file) => file.endsWith('.md') && file !== 'index.md')
    .map((file) => {
      const slug = file.replace(/\.md$/, '')
      const title = readFileSync(join(specsDir, file), 'utf8').match(/^title: '(.*)'$/m)?.[1]
      return { text: title ?? slug, link: `/specs/${slug}` }
    })
    .sort((a, b) => a.text.localeCompare(b.text))
}

const REPO = 'https://github.com/joe-lloyd/git-gud'

export default defineConfig({
  title: 'Git Gud',
  description:
    'A powerful, beautiful Git client with a lane-colored commit graph. Built with Electron + React.',

  // Served from https://joe-lloyd.github.io/git-gud/ — every absolute asset
  // path in markdown gets this prefix automatically.
  base: '/git-gud/',
  cleanUrls: true,
  lastUpdated: true,

  // The app itself is dark-only; the site opens to match, toggle still there.
  appearance: 'dark',

  head: [
    ['link', { rel: 'icon', href: '/git-gud/icon.svg' }],
    ['meta', { name: 'theme-color', content: '#ff4fc3' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:title', content: 'Git Gud — a Git client with a graph worth reading' }],
    ['meta', { property: 'og:image', content: '/git-gud/screenshots/graph.png' }],
  ],

  themeConfig: {
    logo: '/icon.svg',

    nav: [
      { text: 'Install', link: '/install/' },
      { text: 'User guide', link: '/guide/user-guide' },
      { text: 'Git coverage', link: '/guide/git-features' },
      { text: 'Specs', link: '/specs/' },
      {
        text: 'Download',
        items: [
          { text: 'Latest release', link: `${REPO}/releases/latest` },
          { text: 'All releases', link: `${REPO}/releases` },
        ],
      },
    ],

    sidebar: {
      '/install/': [
        {
          text: 'Install',
          items: [
            { text: 'Overview', link: '/install/' },
            { text: 'macOS', link: '/install/macos' },
            { text: 'Windows', link: '/install/windows' },
            { text: 'Linux', link: '/install/linux' },
            { text: 'Build from source', link: '/install/build-from-source' },
            { text: 'Updating', link: '/install/updating' },
          ],
        },
      ],
      '/guide/': [
        {
          text: 'Using Git Gud',
          items: [
            { text: 'User guide', link: '/guide/user-guide' },
            { text: 'Git feature coverage', link: '/guide/git-features' },
          ],
        },
        {
          text: 'Design',
          items: [
            { text: 'Design system', link: '/design/design-system' },
            { text: 'Icon reference', link: '/design/icons' },
          ],
        },
      ],
      '/design/': [
        {
          text: 'Design',
          items: [
            { text: 'Design system', link: '/design/design-system' },
            { text: 'Icon reference', link: '/design/icons' },
          ],
        },
      ],
      '/specs/': [
        {
          text: 'Specifications',
          items: [{ text: 'All capabilities', link: '/specs/' }, ...specSidebar()],
        },
      ],
    },

    search: { provider: 'local' },

    socialLinks: [{ icon: 'github', link: REPO }],

    editLink: {
      pattern: `${REPO}/edit/main/docs/:path`,
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: `Unsigned builds — see the <a href="/git-gud/install/macos">macOS install notes</a>.`,
      copyright: 'Git Gud · built by Joe Lloyd',
    },
  },

  // The synced guides carry GitHub-flavoured links back into the repo; those
  // are absolute URLs, so anything left dead here is a real broken link.
  ignoreDeadLinks: false,
})
