// Copies the repo's real documentation into the VitePress site.
//
// The source of truth stays where it already lives — `docs/` for the guides,
// `openspec/specs/` for the specs, `resources/` for the logo. Nothing here is
// hand-maintained: every path this script writes is gitignored, so the site
// can never drift from the repo. Run before `vitepress dev` / `vitepress build`
// (both npm scripts already do).

import { cp, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const siteDir = dirname(dirname(fileURLToPath(import.meta.url)))
const repoRoot = dirname(siteDir)

/** Directories this script owns end-to-end — wiped first so deletions propagate. */
const GENERATED = ['guide', 'design', 'specs', 'public/screenshots']

// Guides keep their filenames so cross-links between them survive untouched.
const PAGES = [
  { from: 'docs/user-guide.md', to: 'guide/user-guide.md' },
  { from: 'docs/git-features.md', to: 'guide/git-features.md' },
  { from: 'docs/headless.md', to: 'guide/headless.md' },
  { from: 'docs/companion.md', to: 'guide/companion.md' },
  { from: 'docs/relay.md', to: 'guide/relay.md' },
  { from: 'docs/design/design-system.md', to: 'design/design-system.md' },
  { from: 'docs/design/icons.md', to: 'design/icons.md' },
]

/**
 * VitePress compiles markdown as a Vue template, so bare placeholders like
 * `<sha>` or `<branch>` — which GitHub renders as literal text — are parsed as
 * unclosed HTML elements and fail the build. Escape the angle brackets, but
 * only outside fenced blocks and inline code, where they're already inert and
 * escaping would show up as literal `&lt;` on the page.
 *
 * Neither the guides nor the specs contain real HTML (the README does, but it
 * isn't synced), so there's nothing to preserve here. If that changes, this is
 * the function to teach about an allowlist.
 */
function escapePlaceholders(md) {
  // Alternates code / not-code: fences first, then inline spans. Odd indices
  // after each split are the code parts, which pass through untouched.
  return md
    .split(/(^```[\s\S]*?^```$)/gm)
    .map((block, blockIndex) => {
      if (blockIndex % 2 === 1) return block
      return block
        .split(/(`[^`\n]*`)/g)
        .map((span, spanIndex) => (spanIndex % 2 === 1 ? span : span.replace(/</g, '&lt;')))
        .join('')
    })
    .join('')
}

/**
 * Rewrites links that were written for GitHub's markdown renderer so they
 * resolve under VitePress instead.
 */
function rewriteLinks(md) {
  return (
    md
      // `![x](screenshots/y.png)` → site-absolute, so it works from any depth.
      // VitePress prepends the configured `base` to absolute asset paths.
      .replace(/\]\((?:\.\/)?screenshots\//g, '](/screenshots/')
      // `docs/…` prefixes appear in links written from the repo root.
      .replace(/\]\(docs\/screenshots\//g, '](/screenshots/')
      // Drop the `.md` extension — VitePress serves clean URLs.
      .replace(/\]\((\.?\.?\/?[\w./-]+)\.md(#[\w-]*)?\)/g, ']($1$2)')
  )
}

/** `commit-graph` → `Commit graph`, for nav labels and page titles. */
function humanize(slug) {
  const words = slug.replace(/-/g, ' ')
  return words.charAt(0).toUpperCase() + words.slice(1)
}

/** YAML-safe single-quoted scalar. */
function quote(value) {
  return `'${String(value).replace(/'/g, "''")}'`
}

async function syncGuides() {
  for (const { from, to } of PAGES) {
    const src = join(repoRoot, from)
    if (!existsSync(src)) {
      console.warn(`[sync] missing source, skipped: ${from}`)
      continue
    }
    const out = join(siteDir, to)
    await mkdir(dirname(out), { recursive: true })
    await writeFile(out, escapePlaceholders(rewriteLinks(await readFile(src, 'utf8'))))
  }
  console.log(`[sync] guides: ${PAGES.length} pages`)
}

async function syncAssets() {
  await cp(join(repoRoot, 'docs/screenshots'), join(siteDir, 'public/screenshots'), {
    recursive: true,
  })
  await cp(join(repoRoot, 'resources/icon.svg'), join(siteDir, 'public/icon.svg'))
  console.log('[sync] assets: screenshots + logo')
}

/**
 * OpenSpec keeps one `spec.md` per capability directory. Flatten them into
 * `specs/<capability>.md` and build an index. The specs are generated by
 * archiving change proposals, so a chunk of them still carry a placeholder
 * Purpose — those get no blurb rather than a misleading one.
 */
async function syncSpecs() {
  const specsRoot = join(repoRoot, 'openspec/specs')
  if (!existsSync(specsRoot)) {
    console.warn('[sync] no openspec/specs directory, skipped')
    return []
  }

  const entries = (await readdir(specsRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()

  const index = []
  for (const slug of entries) {
    const src = join(specsRoot, slug, 'spec.md')
    if (!existsSync(src)) continue

    const raw = await readFile(src, 'utf8')
    const title = humanize(slug)

    // "## Purpose" body, minus OpenSpec's archiving placeholder.
    const purpose = raw.match(/##\s*Purpose\s*\n+([^\n]+)/)?.[1]?.trim() ?? ''
    const blurb = /^TBD\b/i.test(purpose) ? '' : purpose

    const requirements = (raw.match(/^###\s+Requirement:/gm) ?? []).length

    // Replace the machine-generated `# <slug> Specification` heading with a
    // readable one, and strip the placeholder Purpose block so the page opens
    // on real content.
    const body = escapePlaceholders(
      raw.replace(/^#\s+.*\n/, `# ${title}\n`).replace(/##\s*Purpose\s*\n+TBD[^\n]*\n/, ''),
    )

    const frontmatter = [
      '---',
      `title: ${quote(title)}`,
      blurb ? `description: ${quote(blurb)}` : null,
      '---',
      '',
    ]
      .filter((line) => line !== null)
      .join('\n')

    await writeFile(join(siteDir, 'specs', `${slug}.md`), frontmatter + body)
    index.push({ slug, title, blurb, requirements })
  }

  const total = index.reduce((sum, spec) => sum + spec.requirements, 0)
  const rows = index
    .map(
      (spec) =>
        `| [${spec.title}](/specs/${spec.slug}) | ${spec.requirements} | ${spec.blurb || '—'} |`,
    )
    .join('\n')

  await writeFile(
    join(siteDir, 'specs', 'index.md'),
    `---
title: 'Specifications'
description: 'Every capability in Git Gud, written as testable requirements.'
---

# Specifications

Git Gud is built spec-first: a capability is proposed, specified, implemented,
then the spec is archived here as the standing description of how that part of
the app must behave. Each requirement carries scenarios in
\`WHEN … THEN …\` form, so they double as the acceptance criteria for changes.

**${index.length} capabilities · ${total} requirements.** Source of truth is
[\`openspec/specs/\`](https://github.com/joe-lloyd/git-gud/tree/main/openspec/specs)
in the repo; this page is generated from it.

| Capability | Requirements | Purpose |
| --- | --- | --- |
${rows}
`,
  )

  console.log(`[sync] specs: ${index.length} capabilities, ${total} requirements`)
  return index
}

for (const dir of GENERATED) {
  await rm(join(siteDir, dir), { recursive: true, force: true })
  await mkdir(join(siteDir, dir), { recursive: true })
}

await syncGuides()
await syncAssets()
await syncSpecs()
